version: '3'

services:
  norfair-handtracker:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: python3 /demo/src/app.py
    runtime: nvidia
    volumes:
      - ./src:/demo/src/
    ports:
      - 8001:8001